# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-12-18 08:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20201218_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='profile',
            new_name='profile_pic',
        ),
    ]
